[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
# Usamos npm install normal para asegurar dependencias
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
# Construimos el admin aqu√≠
cmds = ["npm run build"]

[start]
# Arrancamos migraciones y servidor directamente
cmd = "npx medusa db:migrate && npm run start"